//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class estudiantesEntities : DbContext
    {
        public estudiantesEntities()
            : base("name=estudiantesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<contacto> contactoes { get; set; }
        public virtual DbSet<estudiante> estudiantes { get; set; }
        public virtual DbSet<horario> horarios { get; set; }
        public virtual DbSet<registro> registroes { get; set; }
    }
}
