//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class registro
    {
        public int id { get; set; }
        public string Nombre_usuario { get; set; }
        public string contraseña { get; set; }
        public string Matricula { get; set; }
        public string carrera { get; set; }
        public string asignaturas { get; set; }
    }
}
